#!/bin/sh
# Default-deny inbound
iptables -w -P INPUT DROP
iptables -w -P FORWARD DROP
iptables -w -P OUTPUT ACCEPT

# Allow loopback
iptables -w -A INPUT -i lo -j ACCEPT
# Allow established/related
iptables -w -A INPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT

# Allow Bridge over USB gadget interface (usb0) only
iptables -w -A INPUT -i usb0 -p tcp --dport 21324 -j ACCEPT
