#!/bin/sh
### BEGIN INIT INFO
# Provides:          trezor-wallet
# Default-Start:     5
### END INIT INFO

sleep 1
TREZOR_USER=trezor

# Touchscreen / SDL env
export TSLIB_TSDEVICE=/dev/input/touchscreen0
export TSLIB_CALIBFILE=/data/tslib/ts.cal
export TSLIB_CONFFILE=/data/tslib/ts.conf
export SDL_MOUSEDEV=/dev/input/touchscreen0
export SDL_MOUSEDRV=TSLIB
export SDL_VIDEODRIVER=kmsdrm

# Start trezor-bridge if usb0 exists
if ip link show usb0 >/dev/null 2>&1; then
    if [ -x /usr/bin/trezord ]; then
        start-stop-daemon -S -b -m \
            -p /run/trezord.pid \
            -c "${TREZOR_USER}:${TREZOR_USER}" \
            --exec /usr/bin/trezord -- -e 21324 --address 0.0.0.0
    fi
fi

# Start Trezor Core Wallet
if [ -x /usr/bin/trezor-wallet ]; then
    start-stop-daemon -S -b -m \
        -p /run/trezor-core.pid \
        -c "${TREZOR_USER}:${TREZOR_USER}" \
        --exec /usr/bin/trezor-wallet
fi

exit 0