# Funding options for PiTrezor project

custom:
  - "bitcoin:bc1qf2u9emuzsn2hqj3u0ypwuate0ammn2zm2k63gz"
  - "ethereum:0x87efd0009D4abaa4DD91c2B2452AE82CE3430CF6"
  - "solana:3MvBX4m6DzG2bv3ArvscQRBWSMPY1Jiqce5zUjkBfk4d"
  - "https://cash.app/$Truth369"
  - "https://venmo.com/Truth369"
