# Funding options for PiTrezor project

custom: [bc1qf2u9emuzsn2hqj3u0ypwuate0ammn2zm2k63gz, BITCOIN]
custom: [0x87efd0009D4abaa4DD91c2B2452AE82CE3430CF6, ETHEREUM]
custom: [3MvBX4m6DzG2bv3ArvscQRBWSMPY1Jiqce5zUjkBfk4d, SOLANA]
custom: [https://cash.app/$Truth369, Cash App]
custom: [https://venmo.com/Truth369, Venmo]
