# Funding options for PiTrezor project

custom: [bc1qf2u9emuzsn2hqj3u0ypwuate0ammn2zm2k63gz, BITCOIN] [0x87efd0009D4abaa4DD91c2B2452AE82CE3430CF6, ETHEREUM] [3MvBX4m6DzG2bv3ArvscQRBWSMPY1Jiqce5zUjkBfk4d, SOLANA] [https://cash.app/$Truth369, Cash App] [https://venmo.com/Truth369, Venmo]
